Homework2
Kristina970/python-course-alphabet pull request #1
Opened 2019-04-22 10:53 UTC by Kristina970

Homework2 - built_in_methods_iterators
Tests

2019-04-23 10:21 UTC, Kristina970 commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW2_Python_functionality](https://trello.com/c/T7AxeJbs/34-hw2pythonfunctionality)

2019-04-23 12:05 UTC, AndreyPesotskiy commented on build_in_methods_iterators/tests.py
> +        self.assertEqual(task_5_min_value_strings(given_data), 12)
нельзя подстраивать тесты под себя. Результат твоей функции должен возвращать строку

2019-04-23 12:20 UTC, AndreyPesotskiy commented on build_in_methods_iterators/homework.py
> +    return min(data, key=lambda member: member.get('age', 100))
1ое - нужно подставить аргумент приходящий (key) вместо статики "age"
2ое - а что если приходящие данные будут больше 100? Нужно универсально решить для любых приходящих чисел

2019-04-23 18:50 UTC, zulteg commented on build_in_methods_iterators/homework.py
> +    return new_data[0] if new_data else None
Все еще ошибка, тест ожидает строку.
Можно преобразовать возвращаемое значение, например `return str(new_data[0]) ...`

2019-04-23 18:56 UTC, zulteg commented on build_in_methods_iterators/homework.py
> +    return min([item[key] for item in data if key in data], key= lambda x: x[key])
Тут неверно составлен list comprehension, если его запринтить, то он всегда возвращает пустой list
`print([item[key] for item in data if key in data])`

И в метод `min` в `key` ты передаешь лямбда функцию которая работает с dict, хотя в сам min передается list

2019-04-23 19:44 UTC, Kristina970 commented on build_in_methods_iterators/homework.py
> +    return min([item[key] for item in data if key in data], key= lambda x: x[key])
не коректний файл був замерджений

2019-04-23 19:45 UTC, Kristina970 commented on build_in_methods_iterators/homework.py
> +    return new_data[0] if new_data else None
не коректний файл був змерджений

2019-04-23 22:47 UTC, yuriimchg requested changes
до речі, `task_1_fix_names_start_letter` - працює некоректно. Спробуй запустити окремо й порівняти очікування / реальність

2019-04-23 22:47 UTC, yuriimchg commented on build_in_methods_iterators/homework.py
> +    return min(data) if data else None
`return min(data) if data`

2019-04-23 22:47 UTC, yuriimchg commented on build_in_methods_iterators/homework.py
> +    return new_data[0] if new_data else None
тут також не потрібно `else None`

2019-04-23 22:47 UTC, yuriimchg commented on build_in_methods_iterators/homework.py
> +    return new_data[0] if new_data else None
також мені дуже шкода, але це завдання не працює коректно:
```
>>> list_data = 'smoke on the water, fire in the sky'
>>> task_5_min_value_strings(list_data.split()) # 'fire'
``

2019-04-24 20:20 UTC, yuriimchg approved these changes

2019-04-24 20:20 UTC, yuriimchg commented on build_in_methods_iterators/homework.py
> +    new_data = sorted((str(item) for item in data), key=lambda x: len(x))
спробуй також `new_data = sorted((str(item) for item in data), key=len)` :wink:

2019-06-12 11:33 UTC, merged