HW_3_db
Kristina970/python-course-alphabet pull request #3
Opened 2019-04-26 06:08 UTC by Kristina970

2019-04-27 16:29 UTC, yuriimchg requested changes
task_5 - на жаль, такий варіант не працює, потрібно використати інший синтаксинс;
також тести падають на 13 і 16 завданнях

2019-04-27 20:03 UTC, Kristina970 commented
> task_5 - на жаль, такий варіант не працює, потрібно використати інший синтаксинс;
> також тести падають на 13 і 16 завданнях

переписала def 5 
видалила не потрібну колонку з def 13
додала order by до def 16

2019-04-27 20:45 UTC, yuriimchg requested changes

2019-04-27 20:45 UTC, yuriimchg commented on relational_database/homework.py
> +    cursor.execute("DELETE FROM customers WHEREcustomerid = (SELECT MAX(customerid) FROM customers)")
ти хоч пробувала запустити тести після того, як пофіксила завдання?)

2019-04-29 08:03 UTC, Kristina970 commented on relational_database/homework.py
> +    cursor.execute("DELETE FROM customers WHEREcustomerid = (SELECT MAX(customerid) FROM customers)")
не можу пояснити як так сталося, але тест пройшов (з правильним варіантом)

2019-04-30 07:55 UTC, yuriimchg requested changes
привіт, глянув ще раз
120 рядок також не ок
я знаю, що в тестах є помилка, але тут тест падає не через це

також, коли пофіксиш, кидай, будь ласка картку в `in supports`, бо повідомлення з github дуже губляться на пошті

2019-04-30 08:32 UTC, yuriimchg submitted a review, later dismissed

2019-04-30 08:50 UTC, merged