Homework4
Kristina970/python-course-alphabet pull request #4
Opened 2019-05-06 21:01 UTC by Kristina970

2019-05-09 18:28 UTC, yuriimchg requested changes
привіт
переглянув твоє домашнє

загалом досить непогано, але є декілька моментів, які виглядають трохи заплутаними і я не дуже розумію, як вони мали б працювати.

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def __str__(self):
для чого цей метод?

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +        return 'producer: {self.producer}, type: {self.type}, price: {self.price}, ' \
також тут викликається `type`, хоча в тебе є атрибут `car_type`

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def __lt__(self, other):
тут неправильно реалізований метод, 
```
f = Car(price=400, mileage=1, producer='BMW', car_type='Sedan')
sf = Car(price=1400, mileage=1, producer='BMW', car_type='Sedan')
sf < f #True
```

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def __lt__(self, other):
відповідно й `__gt__` і нестрогі нерівності також

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def __lt__(self, other):
тут також методи для нерівностей неправильні

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +        for garage in self.garages:
в мене ця штука не працює

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +            for garage in self.garages:
і, якщо чесно, я не розумію її логіки
для чого двічі ітерувати по гаражах?

2019-05-09 18:28 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +    def __str__(self):
чому тут (і в `Car` та `Garage` ти використовуєш саме `__str__(self)`)

2019-05-09 18:37 UTC, Kristina970 commented on objects_and_classes/homework/homework.py
> +        return 'producer: {self.producer}, type: {self.type}, price: {self.price}, ' \
уп, поправлю

2019-05-09 18:45 UTC, Kristina970 commented on objects_and_classes/homework/homework.py
> +    def __str__(self):
виправляю на __repr__

2019-05-09 19:00 UTC, Kristina970 commented on objects_and_classes/homework/homework.py
> +    def __lt__(self, other):
self.price < other.price

2019-05-09 19:00 UTC, Kristina970 commented on objects_and_classes/homework/homework.py
> +    def __lt__(self, other):
self.hit_hat() < other.hit_hat()

2019-05-10 19:01 UTC, yuriimchg submitted a review, later dismissed

2019-05-18 20:42 UTC, yuriimchg commented
змердж цю і попередню домашню в *`master`*

2019-06-12 11:38 UTC, merged