Homework5
Kristina970/python-course-alphabet pull request #5
Opened 2019-05-13 09:30 UTC by Kristina970

2019-05-16 08:18 UTC, zulteg commented on serialization/homework.py
> +        return Cesar(name=name, garages=garages)
по идее надо в конструктор добавить `register_id`, чтобы сохранять id при создании инстанса с файла

2019-05-16 08:32 UTC, zulteg commented on serialization/homework.py
> +        data = {"name": obj.name, "garages": str(obj.garages), "register_id": str(obj.register_id)}
`"garages": str(obj.garages)` - немного неправильно сохранять так list с объектами. выходит что `garages` это строка, а должен быть массив. например:
```
{
  "name": "John",
  "register_id": "a4401c81-7a2b-4f08-9b93-55ebcf1ab45b",
  "garages": [
    {
      "town": "Kiev",
      "places": 2,
      "owner": "a4401c81-7a2b-4f08-9b93-55ebcf1ab45b",
      "cars": [
        {
          "number": "57073e83-aab3-468a-8768-62b74082d63f",
          "price": 5905.0,
          "car_type": "Wagon",
          "producer": "Bugatti",
          "mileage": 3715.0
        },
        {
          "number": "89f3f4d3-e362-4f56-a0f7-556eeec9840f",
          "price": 16124.0,
          "car_type": "Van",
          "producer": "BENTLEY",
          "mileage": 3574.0
        }
      ]
    },
  ]
}
```

2019-05-16 08:33 UTC, zulteg commented on serialization/homework.py
> +        data = {"name": obj.name, "garages": str(obj.garages), "register_id": str(obj.register_id)}
так же как и с json, в `garages` записывается строка, а не массив

2019-05-20 13:00 UTC, zulteg commented on serialization/homework.py
> +        garages = [garage.to_json_string() for garage in obj.garages]
правильно, ты пробегаешься по всем гаражам, но все еще записываешь строку в list.
чтобы был объект, можно поменять на `garages = [Garage.to_json(garage) for garage in obj.garages]`

2019-05-20 13:00 UTC, zulteg commented on serialization/homework.py
> +        cars = [car.to_json_string() for car in obj.cars]
соответственно тут так же `cars = [Car.to_json(car) for car in obj.cars]`

2019-05-20 13:01 UTC, zulteg commented on serialization/homework.py
> +            return json.dump(self, write_file, default=Cesar.to_json)
для читаемости файла можно добавить `indent=4` в json.dump

2019-05-20 13:04 UTC, zulteg commented on serialization/homework.py
> +        garages = [garage.to_yaml_string() for garage in obj.garages]
тут так же как и с json

2019-05-23 19:16 UTC, yuriimchg requested changes

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +    def __init__(self, name: str, garages=[], register_id=uuid.uuid4()):
` register_id=uuid.uuid4()`
ця штука в тебе не використовується, оскільки ти присвоюєш нове в конструкторі

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +yaml = YAML()
```
yaml = YAML()
```
ти створюєш yaml об'єкт і тут, і в класі Cesar - не треба так)

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +    def __init__(self, name: str, garages=[], register_id=uuid.uuid4()):
також, коли вказуєш типи для одних аргументів, вказуй і для інших, навіть, якщо вони дефолтні

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +    """method to convert python object to json file"""
старайся уникати таких коментарів - краще забабахай докстрінги для методів 
https://dbader.org/blog/python-multiline-comment

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +        with open('cesar_file.json', "r") as file:
`file` - зарезервоване слово в пайтоні, краще назви його інакше
```suggestion
        with open('cesar_file.json', "r") as file:
```
```suggestion
        with open('cesar_file.json', "r") as f:
```

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +        with open('cesar_pickle.file.txt', "wb") as file:
pickle - це потік байтів, відповідно він має зберігатися в бінарному файлі (`.pickle`, `.dat`, інші бінарні формати), але не в текстовому форматі

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +        with open('cesar_pickle.file.txt', "wb") as file:
+ `file`

2019-05-23 19:16 UTC, yuriimchg commented on serialization/homework.py
> +    def from_yaml(cls, data):
чому в тебе перший аргумент методу не `self`?

2019-05-27 20:01 UTC, yuriimchg commented on serialization/homework.py
> +    def to_json(obj: Cesar):
зазвичай прийнято позначати інстанс класу через `self`, а не `obj`

2019-05-27 20:28 UTC, yuriimchg commented on serialization/homework.py
> +from collections import OrderedDict
ще в тебе OrderedDict ніде не використовується

2019-05-27 20:28 UTC, yuriimchg commented on serialization/homework.py
> +    def from_yaml(cls, data):
тут не треба `@classmethod` 
оскільки метод все одно повертає інстанс Цезаря

2019-05-27 20:28 UTC, yuriimchg commented on serialization/homework.py
> +    def to_yaml(obj:Cesar):
а чим відрізняється метод `to_yaml` від `to_json`?

2019-06-09 19:18 UTC, yuriimchg requested changes
привіт,

я переглянув дз
круто, що тобі вдалося позбутися бекслешів :+1: 

ще було б дуже добре трохи покращити стиль коду - можна використати flake8 для цього, але дивись, щоб це не погіршило читабельність коду

також не ок, коли pickle запихається в текстові файли, бо це байти

ще ти не всюди використовуєш `self` як перший аргумент методів - це теж не ок

так

2019-06-09 19:18 UTC, yuriimchg commented on serialization/homework.py
> +    def from_yaml(cls, data):
добре було б, якби цей метод був статичним

2019-06-09 19:18 UTC, yuriimchg commented on serialization/homework.py
> +    def to_json(obj: Garage):
тут потрібно використати `self` як перший аргумент

2019-06-10 19:53 UTC, yuriimchg requested changes
привіт

все ще є те, що треба виправити:
1) порядок імпортів https://www.python.org/dev/peps/pep-0008/#imports
2) pickle не має зберігатися в текстові файли
3) все ще є проблеми зі staticmethod/classmethod

2019-06-10 19:53 UTC, yuriimchg commented on serialization/homework.py
>          with open('cesar_pickle.file.txt', "rb") as file:
`file` - зарезервована назва типу даних, краще вибрати іншу назву (не лише тут)

2019-06-10 19:53 UTC, yuriimchg commented on serialization/homework.py
наступний рядок краще зробити через статичний метод

2019-06-10 19:53 UTC, yuriimchg commented on serialization/homework.py
>          with open('garage_file', "w") as write_file:
garage_file.json

2019-06-10 19:53 UTC, yuriimchg commented on serialization/homework.py
>      def to_yaml_file(self):
garage.yaml

2019-06-11 19:38 UTC, yuriimchg submitted a review, later dismissed
:tada:

2019-06-12 11:47 UTC, merged