Homework6
Kristina970/python-course-alphabet pull request #6
Opened 2019-05-17 08:36 UTC by Kristina970

2019-05-18 20:59 UTC, yuriimchg requested changes
* flake8 свариться на довгі рядки (>79 символів), відступи і ше купу всього.
* інформативність ексепшнів
* все інше в коментарях

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +        self._set_average_speed()
чому б сюди не перемістити `self.average_speed = 0` замість `self._set_average_speed()`? :thinking:

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +            'Such product does not bring you nay value'
```suggestion
            'Such product does not bring you any value'
```

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +            self._reduce_saturation_level(5)
цей випадок нічого не повертає

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +            self._reduce_saturation_level(5)
це не обов'язково, впринципі
але виглядає, ніби цього випадку просто не було в тестах :wink:

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +        count_of_lines_in_roll = math.floor(roll_length_m/self.height)
старайся робити відступи між операторами та змінними (не лише тут)

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +        count_of_lines_in_roll = math.floor(roll_length_m/self.height)
старайся робити відступи між операторами та змінними (не лише тут)

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +                raise ValueError
конструкція try / except тут не потрібна - піднімати помилки можна без неї)
але взагалі виглядає цікаво)

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +                return "Sorry there is only two types of roofs"
сам ексепшн не дуже інформативний, оскільки не каже, **які** саме типи даху можна використати. Але це повідомлення прописане в завданні, тому цей комент швидше за все, на майбутнє

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +        if width <= 0 or height <= 0:
цей код дублюється потім купу разів
так не дуже добре робити
https://uk.wikipedia.org/wiki/Don%27t_repeat_yourself

2019-05-18 20:59 UTC, yuriimchg commented on oop/homework.py
> +# wall = Wall(5, 2.7)
старайся викидати код, який не використовуєш - він тільки захаращує все

2019-05-20 08:51 UTC, Kristina970 commented on oop/homework.py
> +        self._set_average_speed()
ok

2019-05-20 08:52 UTC, Kristina970 commented on oop/homework.py
> +            self._reduce_saturation_level(5)
і тут я зависла, треба це фіксати?

2019-05-20 09:11 UTC, Kristina970 commented on oop/homework.py
> +        if width <= 0 or height <= 0:
але в завданні до House написано: 
Implement method create_wall which will create new wall using class Wall and add it to the __walls list
      it receives parameters width and height
      if width or height eq 0 raise ValueError "Value must be not 0"
      if user have more than 4 walls raise ValueError "Our house can not have more than 4 walls"

2019-05-20 09:11 UTC, Kristina970 commented on oop/homework.py
> +# wall = Wall(5, 2.7)
ок

2019-05-20 09:12 UTC, Kristina970 commented on oop/homework.py
> +                return "Sorry there is only two types of roofs"
дан

2019-05-20 09:12 UTC, Kristina970 commented on oop/homework.py
> +                raise ValueError
дан

2019-05-20 09:12 UTC, Kristina970 commented on oop/homework.py
> +        count_of_lines_in_roll = math.floor(roll_length_m/self.height)
дан

2019-05-20 09:12 UTC, Kristina970 commented on oop/homework.py
> +        count_of_lines_in_roll = math.floor(roll_length_m/self.height)
дан

2019-05-20 14:13 UTC, yuriimchg commented on oop/homework.py
> +            self._reduce_saturation_level(5)
угу

2019-05-20 15:46 UTC, Kristina970 commented on oop/homework.py
> +        self._set_average_speed()
-

2019-06-03 18:52 UTC, yuriimchg submitted a review, later dismissed
перевірив
`+` за підказки типів
`-` за дз, яке попало не туди 

також, якщо матимеш час / натхнення, то можна було б переписати цю дз, не використовуючи `if/else`:wink:
і ще, мердж апрувнуті коміти :slightly_smiling_face:

2019-06-03 18:52 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +
а чому це дз в цьому пул реквесті? :thinking:

2019-06-03 18:52 UTC, yuriimchg commented on oop/homework.py
> +import math
тут краще було б використати `from math import floor`, щоб не імпортувати цілу лібу через одну функцію

2019-06-03 19:05 UTC, Kristina970 commented on objects_and_classes/homework/homework.py
> +
вже нема

2019-06-12 11:48 UTC, merged