homework 9 flask
Kristina970/python-course-alphabet pull request #9
Opened 2019-06-05 15:21 UTC by Kristina970

2019-06-07 05:22 UTC, ekut2104 commented on flask_homework/app.py
> +from flask import Flask, render_template
не вистачає requirements.txt

2019-06-07 05:28 UTC, ekut2104 commented on flask_homework/app.py
> +@app.errorhandler(404)
коли вводиш не правильну адресу отримуєш повідомлення про те що сторінка в розробці)

2019-06-07 05:28 UTC, ekut2104 commented on flask_homework/app.py
> +@app.errorhandler(404)
а мало б бути 404 нот фаунд

2019-06-07 05:31 UTC, ekut2104 commented on flask_homework/app.py
> +@app.errorhandler(404)
і редірект якимось чином ти зробила?

2019-06-07 05:34 UTC, ekut2104 commented on flask_homework/fruits.py
> +fruits = Blueprint('fruits', __name__, template_folder='templates')
зазвичай коли роблять окремий blueprint то template folder теж окрема щоб цей модуль був окремим повнітю

2019-06-07 05:38 UTC, ekut2104 commented on flask_homework/home.py
> +@home.route('/')
можливо title ще передавати звізси а не хардкодити?)

2019-06-07 05:38 UTC, ekut2104 commented on flask_homework/templates/fruits.html
> +{% block title %} Fruits {% endblock %}
я б передавав title  а не хардкодив

2019-06-07 05:41 UTC, ekut2104 commented on flask_homework/app.py
> +@app.route('/interesting')
без тайтлу сторіночка ...не критично але булоб гарніше)

2019-06-07 05:41 UTC, ekut2104 requested changes
непогана робота) є маленькі нюанси)

2019-06-07 08:53 UTC, Kristina970 commented on flask_homework/templates/fruits.html
> +{% block title %} Fruits {% endblock %}
є!

2019-06-07 08:56 UTC, Kristina970 commented on flask_homework/app.py
> +@app.errorhandler(404)
я тут не робила редірект

2019-06-07 08:56 UTC, Kristina970 commented on flask_homework/home.py
> +@home.route('/')
окей

2019-06-09 14:44 UTC, yuriimchg approved these changes
привіт
перевірив, все дуже круто
молодець :+1:
можеш мерджити в мастер

2019-06-12 11:53 UTC, merged